### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by OscarFMdev** [MahdiSohaily/Portfolio#13]
## Debugging description
- I have seen a bug in line 256 in the main.js file. I have surrounded the regular expression with a single quotation, to solve this bug I think you should remove them and keep in mind that the regular expressions should not be surrounded with quotations.
- I have seen a bug in line 280 in the main.js file. In order to store an object in local storage, you have to convert it to a string so I think you have to use JSON.stringify() method to solve the issue

**Comment by MahdiRezaeiDev** [comment]
Thank you for your helpful feedback dear @OscarFMdev.
